

connectionFactory.lifetimeExceeded=해당 연결의 존속시간 [{0}] 밀리초가, 최대 허용치인 [{1}] 밀리초를 초과합니다.

pool.close.fail=데이터베이스 연결 풀을 닫을 수 없습니다.

poolableConnection.validate.fastFail=이 연결에서, 심각한 SQLException이 이전에 발생했습니다.

poolableConnectionFactory.validateObject.fail=Poolable connection이 유효한지 확인하지 못했습니다.

poolingDataSource.factoryConfig=PoolableConnectionFactory가 풀에 연결되지 않았습니다. setPool()을 호출하여 이 설정 문제를 해결합니다.

swallowedExceptionLogger.onSwallowedException=내부 객체 풀이 예외 발생을 무시했습니다.
